### ISSUE TITLE
cuda gpu 0 being used

### ISSUE THREAD

**Issue by nekohacker591** [yangheng95/SuperResolutionAnimeDiffusion#6]
gpu 0 is intergraated

how do i use gpu 1 that is my rtx gpu

**Comment by yangheng95** [comment]
revise the device='cuda:1'

**Comment by nekohacker591** [comment]
> revise the device='cuda:1'

how do i do this i cant know how at all

**Comment by yangheng95** [comment]
https://github.com/yangheng95/SuperResolutionAnimeDiffusion/blob/78241fac560086a19e36b9ad6a41489a54feddf4/app.py#L39

**Comment by nekohacker591** [comment]
> https://github.com/yangheng95/SuperResolutionAnimeDiffusion/blob/78241fac560086a19e36b9ad6a41489a54feddf4/app.py#L39

Traceback (most recent call last):
  File "C:\Users\micha\apps\anime\app.py", line 134, in <module>
    pipe = pipe.to(device)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\diffusers\pipeline_utils.py", line 270, in to
    module.to(torch_device)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\transformers\modeling_utils.py", line 1813, in to
    return super().to(*args, **kwargs)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by nekohacker591** [comment]
i changed that line to device='cuda:1'
