### ISSUE TITLE
how to provent imgs folder from being restored

### ISSUE THREAD

**Issue by nekohacker591** [yangheng95/SuperResolutionAnimeDiffusion#8]
im getting a timeout error  becuase the folder is so big

when i deleted the folder it was recreated along with all the images being restored

is there a way i can delete the backup images

**Comment by nekohacker591** [comment]
this is resulting this this error because its taking too long to load all the images

**Comment by nekohacker591** [comment]
Space built in 242.04 seconds
C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\gradio\blocks.py:1335: DeprecationWarning: The `enable_queue` parameter has been deprecated. Please use the `.queue()` method instead.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\apps\anime\app.py", line 596, in <module>
    demo.launch(debug=is_colab, enable_queue=True, share=is_colab)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\gradio\blocks.py", line 1450, in launch
    if _frontend and (not networking.url_ok(self.local_url)) and (not self.share):
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\gradio\networking.py", line 181, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\micha\anaconda3\envs\diffusion\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

**Comment by nekohacker591** [comment]
read timeout error as in reading all of the images

**Comment by nekohacker591** [comment]
''
@echo off

set folder="imgs"
set delete_count=0

:loop
if exist %folder% (
    if %delete_count%==2 (
        timeout /t 5 /nobreak >nul
        mkdir %folder%
        exit /b
    ) else (
        set /a delete_count+=1
        rmdir /s /q %folder%
        timeout /t 1 /nobreak >nul
    )
) else (
    mkdir %folder%
    timeout /t 1 /nobreak >nul
)
goto loop
''
this is my soft fix

**Comment by nekohacker591** [comment]
i found out how to remove it


for z_file in findfile.find_cwd_files(and_key=['.zip'], exclude_key=['.ignore'], recursive=1):
    with zipfile.ZipFile(z_file, 'r') as zip_ref:
        zip_ref.extractall()
        
        remove this code to fix it
